- name: install build-essential
  apt:
    name: build-essential
    state: present
- name: install gVim
  apt:
    name: vim-gnome
    state: present
- name: install git
  apt:
    name: git
    state: present
- name: install fish
  apt:
    name: fish
    state: present
- name: install Python 3
  apt:
    name: python3
    state: present
- name: Install ag
  apt:
    name: silversearcher-ag
    state: present
- name: Install bvi
  apt:
    name: bvi
    state: present
