---
- hosts: localhost
  vars:
      node_version: v8.9.1
      md5_sum: 7482b2523f72000d1b6060c38945026b
  tasks:
    - name: Be sure we have gcc, make, etc.
      apt:
        name: build-essential
        state: present
    - name: Be sure we have python2
      apt:
        name: python2
        state: present
    - name: Download node.js 
      get_url:
        url: https://nodejs.org/dist/{{node_version}}/node-{{node_version}}.tar.gz
        dest: /tmp/node-{{node_version}}.tar.gz
        force: no
        checksum: md5:{{md5_sum}}
    - name: delete any previous artifacts
      file:
        path: /tmp/node
        state: absent
    - name: create /tmp/node
      file: 
        path: /tmp/node
        state: directory
    - name: unpack node tarball
      unarchive:
        src: /tmp/node-{{node_version}}.tar.gz
        dest: /tmp/node
    - name: configure node.js build
      command: ./configure
      args:
        chdir: /tmp/node/node-{{node_version}}
    - name: make node.js
      command: make -j 5
      args:
        chdir: /tmp/node/node-{{node_version}}
